#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

: "${RECOIL_BAR_CAPTURE_FRAME:=120}"
: "${RECOIL_BAR_PRESENT_CAPTURE_FRAME_COUNT:=60}"
: "${RECOIL_BAR_PRESENT_CAPTURE_QUALITY:=90}"
: "${RECOIL_BAR_PRESENT_CAPTURE_PREFIX:=bar_playability_present}"
: "${RECOIL_BAR_RENDER_MAX_DIFF_PIXELS:=1024}"
: "${RECOIL_BAR_RENDER_MAX_CHANNEL_DELTA:=4}"
: "${RECOIL_BAR_VALIDATION_HIDE_INTERFACE:=0}"
: "${RECOIL_BAR_VALIDATION_CENTER_CAMERA:=0}"
: "${RECOIL_BAR_VALIDATION_PLAYER_START_CAMERA:=0}"
: "${RECOIL_BAR_VALIDATION_SCENE_ONLY:=0}"
: "${RECOIL_BAR_VALIDATION_HIDE_CURSOR:=1}"
: "${RECOIL_BAR_VALIDATION_CAMERA_HEIGHT:=1200}"
: "${RECOIL_BAR_VALIDATION_CAMERA_BACK_OFFSET:=900}"
: "${RECOIL_BAR_SMOKE_HIDDEN:=0}"

if [ -z "${RECOIL_BAR_PRESENT_CAPTURE_START_FRAME:-}" ]; then
	RECOIL_BAR_PRESENT_CAPTURE_START_FRAME=$((RECOIL_BAR_CAPTURE_FRAME - RECOIL_BAR_PRESENT_CAPTURE_FRAME_COUNT + 1))

	if [ "$RECOIL_BAR_PRESENT_CAPTURE_START_FRAME" -lt 1 ]; then
		RECOIL_BAR_PRESENT_CAPTURE_START_FRAME=1
	fi
fi

export RECOIL_BAR_CAPTURE_FRAME
export RECOIL_BAR_PRESENT_CAPTURE_START_FRAME
export RECOIL_BAR_PRESENT_CAPTURE_FRAME_COUNT
export RECOIL_BAR_PRESENT_CAPTURE_QUALITY
export RECOIL_BAR_PRESENT_CAPTURE_PREFIX
export RECOIL_BAR_RENDER_MAX_DIFF_PIXELS
export RECOIL_BAR_RENDER_MAX_CHANNEL_DELTA
export RECOIL_BAR_VALIDATION_HIDE_INTERFACE
export RECOIL_BAR_VALIDATION_CENTER_CAMERA
export RECOIL_BAR_VALIDATION_PLAYER_START_CAMERA
export RECOIL_BAR_VALIDATION_SCENE_ONLY
export RECOIL_BAR_VALIDATION_HIDE_CURSOR
export RECOIL_BAR_VALIDATION_CAMERA_HEIGHT
export RECOIL_BAR_VALIDATION_CAMERA_BACK_OFFSET
export RECOIL_BAR_SMOKE_HIDDEN

exec "$SCRIPT_DIR/run-bar-realcontent-smoke.sh" "$@"
