# Builds docker images used by engine-build.yml
name: Docker Images Build
on:
  workflow_dispatch:
    inputs:
      update-digests:
        description: "Commit new image versions to branch"
        type: boolean
        default: true
  push:
    branches:
      - master
    paths:
      - "docker-build-v2/images/**"
  pull_request:
    paths:
      - "docker-build-v2/images/**"
jobs:
  build-images:
    if: github.repository == 'beyond-all-reason/RecoilEngine' || github.event_name == 'workflow_dispatch'
    name: Build ${{ matrix.system.target }} docker image
    runs-on: ${{ matrix.system.runs-on }}
    strategy:
      matrix:
        system:
          - target: amd64-linux
            runs-on: ubuntu-24.04
          - target: arm64-linux
            runs-on: ubuntu-24.04-arm
          - target: amd64-windows
            runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          # Disabling cache to make sure that operations like git clone are
          # not cached and we always pull freshest libs. New images are build
          # quite rarely so it's not an issue performance wise.
          docker-build-v2/images/${{ matrix.system.target }}/build.sh --no-cache
          docker image save recoil-build-${{ matrix.system.target }}:latest --output ${{ runner.temp }}/image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-image-${{ matrix.system.target }}
          path: ${{ runner.temp }}/image.tar
  test-build:
    needs: build-images
    uses: ./.github/workflows/engine-build.yml
    with:
      image-artifacts: true
    secrets: inherit
  publish:
    name: Push images and update digests
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.update-digests == true
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download image artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: build-image-*
          path: ${{ runner.temp }}/images
      - name: Push images and update digests
        run: |
          for system in amd64-linux arm64-linux amd64-windows; do
            docker load --input ${{ runner.temp }}/images/build-image-$system/image.tar
            docker tag recoil-build-$system:latest ghcr.io/${{ github.repository_owner }}/recoil-build-$system:latest
            docker push ghcr.io/${{ github.repository_owner }}/recoil-build-$system:latest | tee ${{ runner.temp }}/push_output.txt
            digest=$(tail -n 1 ${{ runner.temp }}/push_output.txt | cut -d' ' -f 3)
            sed -i -r "s/(image_version\[$system\]=)(.*)/\1$digest/" docker-build-v2/images_versions.sh
          done
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automatic docker build image update from ${{ github.sha }}
